In [27]:
import pandas as pd

In [28]:
df = pd.read_csv("data/ANNUAL_TRADE_YEAR_PRODUCT_COUNTRY.csv")
df

,Year,Source,Product Name,Country Name,Volume (kg),Value (USD),Calculated Duty (USD),Edible code
0,1995,IMP,GROUNDFISH OCEAN PERCH NSPF FROZEN,ICELAND,"5,313","16,234",48,E
1,2003,IMP,GROUNDFISH COD NSPF FILLET DRIED/SALTED/BRINE ...,NORWAY,"368,841","3,083,112",0,E
2,1991,IMP,GROUNDFISH COD NSPF FILLET DRIED/SALTED/BRINE ...,NORWAY,"13,383","49,326",0,E
3,2007,IMP,GROUNDFISH HADDOCK FILLET FRESH,ICELAND,"2,640","32,294",0,E
4,1991,IMP,GROUNDFISH WHITING FILLET BLOCKS FROZEN > 4.5KG,PORTUGAL,"2,887","10,407",0,E
...,...,...,...,...,...,...,...,...
8778,2018,IMP,GROUNDFISH NSPF FILLET FROZEN,ICELAND,"328,419","1,596,981",0,E
8779,2021,IMP,GROUNDFISH COD NSPF DRIED,PORTUGAL,"5,675","63,720",0,E
8780,2020,IMP,GROUNDFISH COD ATLANTIC FRESH,NORWAY,"4,538","34,399",0,E
8781,2023,IMP,GROUNDFISH COD ATLANTIC FILLET FRESH,ICELAND,"20,140","412,773",0,E
8782,2024,IMP,GROUNDFISH COD ATLANTIC FILLET FRESH,ICELAND,"14,185","207,075",0,E

In [29]:
print(df.columns)

Index(['Year', 'Source', 'Product Name', 'Country Name', 'Volume (kg)',
       'Value (USD)', 'Calculated Duty (USD)', 'Edible code'],
      dtype='object')

In [30]:
df['Year'] = df['Year'].astype(int)
df["Volume (kg)"] = df["Volume (kg)"].str.replace("\,", "")
df["Value (USD)"] = df["Value (USD)"].str.replace("\,", "")

In [ ]:
df = df[(df['Year'] >= 2009) & (df['Year'] <= 2021)]

In [39]:
df["Volume (kg)"] = df["Volume (kg)"].str.replace(",", "").astype(int)

In [40]:
df["Value (USD)"] = df["Value (USD)"].str.replace(",", "").astype(int)

In [41]:
df

,Year,Source,Product Name,Country Name,Volume (kg),Value (USD),Calculated Duty (USD),Edible code
0,2014,IMP,GROUNDFISH COD ATLANTIC FRESH,UNITED KINGDOM,4492,12268,0,E
1,2015,IMP,GROUNDFISH NSPF MEAT FRESH,ICELAND,698816,5602428,0,E
2,2011,IMP,GROUNDFISH HADDOCK FILLET BLOCKS FROZEN > 4.5KG,NORWAY,34042,165968,0,E
3,2014,IMP,GROUNDFISH NSPF FILLET FRESH,ICELAND,145,2080,0,E
4,2018,IMP,GROUNDFISH COD NSPF MEAT FROZEN > 6.8KG,SPAIN,2346,31863,0,E
...,...,...,...,...,...,...,...,...
2048,2016,IMP,GROUNDFISH COD ATLANTIC MEAT FRESH,ICELAND,68653,963689,0,E
2049,2017,IMP,GROUNDFISH CUSK FILLET FROZEN,NORWAY,2140,4237,0,E
2050,2018,IMP,GROUNDFISH NSPF FILLET FROZEN,ICELAND,328419,1596981,0,E
2051,2021,IMP,GROUNDFISH COD NSPF DRIED,PORTUGAL,5675,63720,0,E
2052,2020,IMP,GROUNDFISH COD ATLANTIC FRESH,NORWAY,4538,34399,0,E

In [33]:
df = df.reset_index(drop=True)

In [34]:
df

,Year,Source,Product Name,Country Name,Volume (kg),Value (USD),Calculated Duty (USD),Edible code
0,2014,IMP,GROUNDFISH COD ATLANTIC FRESH,UNITED KINGDOM,"4,492","12,268",0,E
1,2015,IMP,GROUNDFISH NSPF MEAT FRESH,ICELAND,"698,816","5,602,428",0,E
2,2011,IMP,GROUNDFISH HADDOCK FILLET BLOCKS FROZEN > 4.5KG,NORWAY,"34,042","165,968",0,E
3,2014,IMP,GROUNDFISH NSPF FILLET FRESH,ICELAND,145,"2,080",0,E
4,2018,IMP,GROUNDFISH COD NSPF MEAT FROZEN > 6.8KG,SPAIN,"2,346","31,863",0,E
...,...,...,...,...,...,...,...,...
2048,2016,IMP,GROUNDFISH COD ATLANTIC MEAT FRESH,ICELAND,"68,653","963,689",0,E
2049,2017,IMP,GROUNDFISH CUSK FILLET FROZEN,NORWAY,"2,140","4,237",0,E
2050,2018,IMP,GROUNDFISH NSPF FILLET FROZEN,ICELAND,"328,419","1,596,981",0,E
2051,2021,IMP,GROUNDFISH COD NSPF DRIED,PORTUGAL,"5,675","63,720",0,E
2052,2020,IMP,GROUNDFISH COD ATLANTIC FRESH,NORWAY,"4,538","34,399",0,E

In [35]:
m = df['Year'].min()
m

2009

In [36]:
sorted_df = df.sort_values(by='Year')
sorted_df
sorted_df = sorted_df.reset_index(drop=True)
sorted_df
sorted_df.to_csv("processed_NE_data.csv")